-- admin/admin calculated by https://bcrypt-generator.com/
--INSERT INTO PERSON (USERNAME, PASSWORD_HASH, ROLE) VALUES ('admin', '$2a$12$jYJYfiKpP7QRK9nCg9E9ueoHB0vg546SyvgHAeLpGIESaNXg734JO', 'ADMIN');

--INSERT INTO SYSTEM_USER (FIRST_NAME, LAST_NAME, USERNAME, EMAIL, PHONE, PASSWORD, USER_ROLE) values ('admin', 'LAST NAME', 'ADMIN', 'admin@admin.com', NULL, '$2a$12$jYJYfiKpP7QRK9nCg9E9ueoHB0vg546SyvgHAeLpGIESaNXg734JO', 'ADMIN');